//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MngrPaycheck.CommunicationCommon.ProductServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceRef.IProductRepositoryService", CallbackContract=typeof(MngrPaycheck.CommunicationCommon.ProductServiceRef.IProductRepositoryServiceCallback))]
    public interface IProductRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductRepositoryService/GetAll", ReplyAction="http://tempuri.org/IProductRepositoryService/GetAllResponse")]
        string GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductRepositoryService/Add", ReplyAction="http://tempuri.org/IProductRepositoryService/AddResponse")]
        void Add(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductRepositoryService/Delete", ReplyAction="http://tempuri.org/IProductRepositoryService/DeleteResponse")]
        void Delete(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductRepositoryService/Update", ReplyAction="http://tempuri.org/IProductRepositoryService/UpdateResponse")]
        void Update(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductRepositoryService/Subscribe", ReplyAction="http://tempuri.org/IProductRepositoryService/SubscribeResponse")]
        System.Guid Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProductRepositoryService/Unsubscribe")]
        void Unsubscribe(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProductRepositoryService/KeepConnection")]
        void KeepConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductRepositoryService/SendMessage", ReplyAction="http://tempuri.org/IProductRepositoryService/SendMessageResponse")]
        void SendMessage(System.Guid clientId, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductRepositoryServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProductRepositoryService/HandleMessage")]
        void HandleMessage(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductRepositoryServiceChannel : MngrPaycheck.CommunicationCommon.ProductServiceRef.IProductRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductRepositoryServiceClient : System.ServiceModel.DuplexClientBase<MngrPaycheck.CommunicationCommon.ProductServiceRef.IProductRepositoryService>, MngrPaycheck.CommunicationCommon.ProductServiceRef.IProductRepositoryService {
        
        public ProductRepositoryServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ProductRepositoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ProductRepositoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProductRepositoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ProductRepositoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(string json) {
            base.Channel.Add(json);
        }
        
        public void Delete(string json) {
            base.Channel.Delete(json);
        }
        
        public void Update(string json) {
            base.Channel.Update(json);
        }
        
        public System.Guid Subscribe() {
            return base.Channel.Subscribe();
        }
        
        public void Unsubscribe(System.Guid clientId) {
            base.Channel.Unsubscribe(clientId);
        }
        
        public void KeepConnection() {
            base.Channel.KeepConnection();
        }
        
        public void SendMessage(System.Guid clientId, string message) {
            base.Channel.SendMessage(clientId, message);
        }
    }
}
