//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MngrPaycheck.CommunicationCommon.PurchaseServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PurchaseServiceRef.IPurchaseRepositoryService")]
    public interface IPurchaseRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseRepositoryService/GetAll", ReplyAction="http://tempuri.org/IPurchaseRepositoryService/GetAllResponse")]
        string GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseRepositoryService/Add", ReplyAction="http://tempuri.org/IPurchaseRepositoryService/AddResponse")]
        void Add(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseRepositoryService/Delete", ReplyAction="http://tempuri.org/IPurchaseRepositoryService/DeleteResponse")]
        void Delete(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseRepositoryService/Update", ReplyAction="http://tempuri.org/IPurchaseRepositoryService/UpdateResponse")]
        void Update(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseRepositoryServiceChannel : MngrPaycheck.CommunicationCommon.PurchaseServiceRef.IPurchaseRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseRepositoryServiceClient : System.ServiceModel.ClientBase<MngrPaycheck.CommunicationCommon.PurchaseServiceRef.IPurchaseRepositoryService>, MngrPaycheck.CommunicationCommon.PurchaseServiceRef.IPurchaseRepositoryService {
        
        public PurchaseRepositoryServiceClient() {
        }
        
        public PurchaseRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(string json) {
            base.Channel.Add(json);
        }
        
        public void Delete(string json) {
            base.Channel.Delete(json);
        }
        
        public void Update(string json) {
            base.Channel.Update(json);
        }
    }
}
