//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MngrPaycheck.Administrator.ProductTypeServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductTypeServiceRef.IProductTypeRepositoryService")]
    public interface IProductTypeRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductTypeRepositoryService/GetAll", ReplyAction="http://tempuri.org/IProductTypeRepositoryService/GetAllResponse")]
        string GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductTypeRepositoryService/Add", ReplyAction="http://tempuri.org/IProductTypeRepositoryService/AddResponse")]
        void Add(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductTypeRepositoryService/Delete", ReplyAction="http://tempuri.org/IProductTypeRepositoryService/DeleteResponse")]
        void Delete(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductTypeRepositoryService/Update", ReplyAction="http://tempuri.org/IProductTypeRepositoryService/UpdateResponse")]
        void Update(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductTypeRepositoryServiceChannel : MngrPaycheck.Administrator.ProductTypeServiceRef.IProductTypeRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductTypeRepositoryServiceClient : System.ServiceModel.ClientBase<MngrPaycheck.Administrator.ProductTypeServiceRef.IProductTypeRepositoryService>, MngrPaycheck.Administrator.ProductTypeServiceRef.IProductTypeRepositoryService {
        
        public ProductTypeRepositoryServiceClient() {
        }
        
        public ProductTypeRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductTypeRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductTypeRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductTypeRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(string json) {
            base.Channel.Add(json);
        }
        
        public void Delete(string json) {
            base.Channel.Delete(json);
        }
        
        public void Update(string json) {
            base.Channel.Update(json);
        }
    }
}
