//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MngrPaycheck.Administrator.ProductParameterValueServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductParameterValueServiceReference.IProductParameterValueRepositoryService")]
    public interface IProductParameterValueRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepositoryService/GetParameterValues", ReplyAction="http://tempuri.org/IProductParameterValueRepositoryService/GetParameterValuesResp" +
            "onse")]
        string GetParameterValues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepositoryService/GetParameterValues", ReplyAction="http://tempuri.org/IProductParameterValueRepositoryService/GetParameterValuesResp" +
            "onse")]
        System.Threading.Tasks.Task<string> GetParameterValuesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepositoryService/AddParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepositoryService/AddParameterValueRespo" +
            "nse")]
        void AddParameterValue(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepositoryService/AddParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepositoryService/AddParameterValueRespo" +
            "nse")]
        System.Threading.Tasks.Task AddParameterValueAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepositoryService/DeleteParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepositoryService/DeleteParameterValueRe" +
            "sponse")]
        void DeleteParameterValue(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepositoryService/DeleteParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepositoryService/DeleteParameterValueRe" +
            "sponse")]
        System.Threading.Tasks.Task DeleteParameterValueAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepositoryService/UpdateParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepositoryService/UpdateParameterValueRe" +
            "sponse")]
        void UpdateParameterValue(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepositoryService/UpdateParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepositoryService/UpdateParameterValueRe" +
            "sponse")]
        System.Threading.Tasks.Task UpdateParameterValueAsync(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductParameterValueRepositoryServiceChannel : MngrPaycheck.Administrator.ProductParameterValueServiceReference.IProductParameterValueRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductParameterValueRepositoryServiceClient : System.ServiceModel.ClientBase<MngrPaycheck.Administrator.ProductParameterValueServiceReference.IProductParameterValueRepositoryService>, MngrPaycheck.Administrator.ProductParameterValueServiceReference.IProductParameterValueRepositoryService {
        
        public ProductParameterValueRepositoryServiceClient() {
        }
        
        public ProductParameterValueRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductParameterValueRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductParameterValueRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductParameterValueRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetParameterValues() {
            return base.Channel.GetParameterValues();
        }
        
        public System.Threading.Tasks.Task<string> GetParameterValuesAsync() {
            return base.Channel.GetParameterValuesAsync();
        }
        
        public void AddParameterValue(string json) {
            base.Channel.AddParameterValue(json);
        }
        
        public System.Threading.Tasks.Task AddParameterValueAsync(string json) {
            return base.Channel.AddParameterValueAsync(json);
        }
        
        public void DeleteParameterValue(string json) {
            base.Channel.DeleteParameterValue(json);
        }
        
        public System.Threading.Tasks.Task DeleteParameterValueAsync(string json) {
            return base.Channel.DeleteParameterValueAsync(json);
        }
        
        public void UpdateParameterValue(string json) {
            base.Channel.UpdateParameterValue(json);
        }
        
        public System.Threading.Tasks.Task UpdateParameterValueAsync(string json) {
            return base.Channel.UpdateParameterValueAsync(json);
        }
    }
}
