using System.Reflection;

// NB! this file is automatically generated. All manual changes will be lost on build.
// Check ~/_tools/Nortal.Utilities.AssemblyVersioning.props file for other available algorithms and supported attributes.

// Generated based on assembly version: 1.0.0.0
[assembly: AssemblyInformationalVersion(@"1.0.0-Debug-20151110-2045")] // algorithm: NugetSemanticVersionGenerator
