//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MngrPaycheck.Administrator.ProductParameterValueServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductParameterValueServiceRef.IProductParameterValueRepository")]
    public interface IProductParameterValueRepository {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepository/GetParameterValues", ReplyAction="http://tempuri.org/IProductParameterValueRepository/GetParameterValuesResponse")]
        string GetParameterValues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepository/GetParameterValues", ReplyAction="http://tempuri.org/IProductParameterValueRepository/GetParameterValuesResponse")]
        System.Threading.Tasks.Task<string> GetParameterValuesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepository/AddParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepository/AddParameterValueResponse")]
        void AddParameterValue(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepository/AddParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepository/AddParameterValueResponse")]
        System.Threading.Tasks.Task AddParameterValueAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepository/DeleteParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepository/DeleteParameterValueResponse")]
        void DeleteParameterValue(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepository/DeleteParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepository/DeleteParameterValueResponse")]
        System.Threading.Tasks.Task DeleteParameterValueAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepository/UpdateParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepository/UpdateParameterValueResponse")]
        void UpdateParameterValue(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductParameterValueRepository/UpdateParameterValue", ReplyAction="http://tempuri.org/IProductParameterValueRepository/UpdateParameterValueResponse")]
        System.Threading.Tasks.Task UpdateParameterValueAsync(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductParameterValueRepositoryChannel : MngrPaycheck.Administrator.ProductParameterValueServiceRef.IProductParameterValueRepository, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductParameterValueRepositoryClient : System.ServiceModel.ClientBase<MngrPaycheck.Administrator.ProductParameterValueServiceRef.IProductParameterValueRepository>, MngrPaycheck.Administrator.ProductParameterValueServiceRef.IProductParameterValueRepository {
        
        public ProductParameterValueRepositoryClient() {
        }
        
        public ProductParameterValueRepositoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductParameterValueRepositoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductParameterValueRepositoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductParameterValueRepositoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetParameterValues() {
            return base.Channel.GetParameterValues();
        }
        
        public System.Threading.Tasks.Task<string> GetParameterValuesAsync() {
            return base.Channel.GetParameterValuesAsync();
        }
        
        public void AddParameterValue(string json) {
            base.Channel.AddParameterValue(json);
        }
        
        public System.Threading.Tasks.Task AddParameterValueAsync(string json) {
            return base.Channel.AddParameterValueAsync(json);
        }
        
        public void DeleteParameterValue(string json) {
            base.Channel.DeleteParameterValue(json);
        }
        
        public System.Threading.Tasks.Task DeleteParameterValueAsync(string json) {
            return base.Channel.DeleteParameterValueAsync(json);
        }
        
        public void UpdateParameterValue(string json) {
            base.Channel.UpdateParameterValue(json);
        }
        
        public System.Threading.Tasks.Task UpdateParameterValueAsync(string json) {
            return base.Channel.UpdateParameterValueAsync(json);
        }
    }
}
