//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MngrPaycheck.Buyer.BuyerServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BuyerServiceRef.IBuyerRepositoryService")]
    public interface IBuyerRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuyerRepositoryService/GetAll", ReplyAction="http://tempuri.org/IBuyerRepositoryService/GetAllResponse")]
        string GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuyerRepositoryService/Add", ReplyAction="http://tempuri.org/IBuyerRepositoryService/AddResponse")]
        void Add(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuyerRepositoryService/Delete", ReplyAction="http://tempuri.org/IBuyerRepositoryService/DeleteResponse")]
        void Delete(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuyerRepositoryService/Update", ReplyAction="http://tempuri.org/IBuyerRepositoryService/UpdateResponse")]
        void Update(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuyerRepositoryServiceChannel : MngrPaycheck.Buyer.BuyerServiceRef.IBuyerRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuyerRepositoryServiceClient : System.ServiceModel.ClientBase<MngrPaycheck.Buyer.BuyerServiceRef.IBuyerRepositoryService>, MngrPaycheck.Buyer.BuyerServiceRef.IBuyerRepositoryService {
        
        public BuyerRepositoryServiceClient() {
        }
        
        public BuyerRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuyerRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuyerRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuyerRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(string json) {
            base.Channel.Add(json);
        }
        
        public void Delete(string json) {
            base.Channel.Delete(json);
        }
        
        public void Update(string json) {
            base.Channel.Update(json);
        }
    }
}
