//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MngrPaycheck.PurchaseProductServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PurchaseProductServiceRef.IPurchaseProductRepositoryService")]
    public interface IPurchaseProductRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseProductRepositoryService/GetAll", ReplyAction="http://tempuri.org/IPurchaseProductRepositoryService/GetAllResponse")]
        string GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseProductRepositoryService/Add", ReplyAction="http://tempuri.org/IPurchaseProductRepositoryService/AddResponse")]
        void Add(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseProductRepositoryService/Delete", ReplyAction="http://tempuri.org/IPurchaseProductRepositoryService/DeleteResponse")]
        void Delete(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseProductRepositoryService/Update", ReplyAction="http://tempuri.org/IPurchaseProductRepositoryService/UpdateResponse")]
        void Update(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseProductRepositoryServiceChannel : MngrPaycheck.PurchaseProductServiceRef.IPurchaseProductRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseProductRepositoryServiceClient : System.ServiceModel.ClientBase<MngrPaycheck.PurchaseProductServiceRef.IPurchaseProductRepositoryService>, MngrPaycheck.PurchaseProductServiceRef.IPurchaseProductRepositoryService {
        
        public PurchaseProductRepositoryServiceClient() {
        }
        
        public PurchaseProductRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseProductRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseProductRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseProductRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAll() {
            return base.Channel.GetAll();
        }
        
        public void Add(string json) {
            base.Channel.Add(json);
        }
        
        public void Delete(string json) {
            base.Channel.Delete(json);
        }
        
        public void Update(string json) {
            base.Channel.Update(json);
        }
    }
}
